version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "17:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    reviewers:
      - SmolSoftBoi
    labels:
      - dependencies
    versioning-strategy: increase
    rebase-strategy: auto
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "17:00"
      timezone: Europe/London
