name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Eslint
        run: npm run css-lint
